---
- name: install httpd
  hosts: localhost
  tasks: 
  - name: install httpd
    yum: 
     name: httpd
     state: latest
    register: httpdinstall
  - name: print httpdinstall
    debug: 
     msg: "{{httpdinstall}}"
